---
port: '8082'
db_url: Oracle://user:password@localhost:5432/petstore?sslmode=disable
jaeger_url: http://jaeger:16682
sentry_url: http://sentry:9002
kafka_broker: kafka:9092
some_app_id: testid_2
some_app_key: testkey_2
users:
- name: Sam
  id: 1
- name: Bob
  id: 2
